import pytest
from acme import Product
from acme_report import *


def test_default_values():
    '''Check for the expected default values
        in the Product class'''
    prod = Product('Ball')
    assert prod.price == 10
    assert prod.weight == 20
    assert prod.flammability == 0.5
    

def test_methods():
    '''Confirm the expected results for the
        stealability() and explode() methods
        of the Product class'''
    prod = Product('Ball', 10, 25, 2.33)
    assert prod.stealability() == 'is a not so stealable product!'
    assert prod.explode() == '...BABOOM!!'


def test_default_num_products():
    '''Confirm the default lenght (30) of the
        product list generated by generate_products()'''
    products_list = generate_products()
    assert len(products_list) == 30


def test_legal_names():
    '''checks that the generated names for a default batch
        of products are all valid possible names to generate
        (adjective, space, noun, from the lists of possible words)'''
    products_list = generate_products()
    for i in products_list:
        adjective, noun = i.split()
        assert adjective in adjectives
        assert noun in nouns
